// Common
export const LOADING_DATA_START: string = "LOADING_DATA_START";
export const LOADING_DATA_STOP: string = "LOADING_DATA_STOP";

// Homepage
export const GET_HOMEPAGE_DATA_PRISMIC: string = "GET_HOMEPAGE_DATA_PRISMIC";

// Articles
export const GET_ALL_ARTICLES: string = "GET_ALL_ARTICLES";
export const GET_ALL_ARTICLES_INITIAL_STATE: string =
  "GET_ALL_ARTICLES_INITIAL_STATE";
export const SET_ERROR_ALL_ARTICLES_TRUE: string =
  "SET_ERROR_ALL_ARTICLES_TRUE";
export const SET_ERROR_ALL_ARTICLES_FALSE: string =
  "SET_ERROR_ALL_ARTICLES_FALSE";

// Single Article
export const GET_ARTICLE_BY_UID: string = "GET_ARTICLE_BY_UID";
export const GET_3_LAST_ARTICLES: string = "GET_3_LAST_ARTICLES";
export const SET_ERROR_SINGLE_ARTICLE_TRUE: string =
  "SET_ERROR_SINGLE_ARTICLE_TRUE";
// export const SET_ERROR_SINGLE_ARTICLE_FALSE: string = "SET_ERROR_SINGLE_ARTICLE_FALSE";
export const SET_CURRENT_ARTICLE_UID: string = "SET_CURRENT_ARTICLE_UID";

// Author
export const GET_AUTHOR_BY_UID: string = "GET_AUTHOR_BY_UID";
export const SET_ERROR_AUTHOR_BY_UID_TRUE: string = "ERROR_AUTHOR_BY_UID_TRUE";
//export const SET_ERROR_AUTHOR_BY_UID_FALSE: string = "SET_ERROR_AUTHOR_BY_UID_FALSE";

// Search
export const SET_SEARCH_TEXT: string = "SET_SEARCH_TEXT";
export const GET_ARTICLES_BY_SEARCH_TEXT: string =
  "GET_ARTICLES_BY_SEARCH_TEXT";
export const SET_LOADING_SEARCH_START: string = "SET_LOADING_SEARCH_START";
export const SET_LOADING_SEARCH_STOP: string = "SET_LOADING_SEARCH_STOP";
export const SET_ERROR_SEARCH_TEXT_TRUE: string = "SET_ERROR_SEARCH_TEXT_TRUE";
export const SET_ERROR_SEARCH_TEXT_FALSE: string =
  "SET_ERROR_SEARCH_TEXT_FALSE";

// Mailchimp
export const SUBSCRIBE_TO_MAILCHIMP: string = "SUBSCRIBE_TO_MAILCHIMP";
export const SET_LOADING_START_MAILCHIMP: string =
  "SET_LOADING_START_MAILCHIMP";
export const SET_LOADING_STOP_MAILCHIMP: string = "SET_LOADING_STOP_MAILCHIMP";
export const SET_MAILCHIMP_ERROR_TRUE: string = "SET_MAILCHIMP_ERROR_TRUE";
export const SET_MAILCHIMP_ERROR_FALSE: string = "SET_MAILCHIMP_ERROR_FALSE";
